language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      ppa:ubuntu-toolchain-r/test
    packages:
      libstdc++-4.8-dev
      freeglut3-dev
      cmake

before_install:
  - echo $LANG
  - echo $LC_ALL

script: 
  - ./compile.sh
  - ./build/Raytracer
