language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - freeglut3-dev
      - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL

script: 
  - ./compile.sh
  - ./build/Raytracer
