language: cpp
sudo: false
compiler: gcc
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - cmake
      - libpng++-dev

before_install:
  - echo $LANG
  - echo $LC_ALL

script: 
  - ./compileAndTest.sh
